#!/bin/bash
# This is not meant to be run, these are just some of the commands to get the .vimrc and the plugins it uses
# getPlugins.sh will get the plugins after initialisation
# Otherwise copying and pasting the following should download and set up everything
cd ~
mv .vim .vim.bkp
mv .vimrc .vimrc.bkp
git clone https://github.com/mikesligo/.vim.git
ln -s .vim/.vimrc ~/
cd .vim
git submodule init
git submodule update

# update
git pull origin master
git submodule foreach git pull origin master

# How to delete a submodule:
# 1. Remove it from .gitmodules
# 2. Remove it from .git/config
# 3. Run git rm --cached <path-to-module></path-to-module>
