#!/bin/bash
cd ~
mv .vim .vim.bkp
mv .vimrc .vimrc.bkp
git clone https://github.com/mikesligo/.vim.git
ln -s .vim/.vimrc ~/
cd .vim
git submodule init
git submodule update

# update
# git pull origin master
# git submodule foreach git pull origin master

# How to delete a submodule:
# 1. Remove it from .gitmodules
# 2. Remove it from .git/config
# 3. Run git rm --cached <path-to-module></path-to-module>
